# Site settings
title: Anonymous function
header-img: img/home-bg.png
email: aniqaelahi@yahoo.com
copyright_name: anniezh12
description: > # this means to ignore newlines until "baseurl:"
  Merging code with  life
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  anniezh12
learn_profile: anniezh12
email_username: aniqaelahi@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
